### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by renderorange**
added line for current status of project, since it's been a number of years since any activity has happened.

### CODE REVIEW

**Comment by endofcake** [comment]
Ironically, this PR is unlikely to get merged for this very reason.

**Comment by renderorange** [comment]
heh :)

**Comment by zachlatta** [comment]
Good call – really sorry for dropping the ball on staying on top of things with this.

**Comment by zachlatta** [comment]
One thought is to add everyone who gets a PR merged as a collaborator to the repo. I believe http://rubini.us/ did/does this and I recently chatted with @feross who _highly_ recommended having an open commit bit as well.

I just sent an email to @marcuswhybrow to see what he thinks.

**Comment by kjkazinski** [comment]
Has the version number been updated and a new version available with all the fixes people have been making?

**Comment by endofcake** [comment]
@kjkazinski , I haven't thought about that, I just wanted to fix an annoying bug. Could you do this now that we have someone with merge rights?

**Comment by kjkazinski** [comment]
Alexander - I don't have merge rights but I was hoping Marcus would give it to some of the more active people.  I am new to git and don't really get how to use it.  I always thought SVN was much simpler to understand the work flow.

**Comment by zachlatta** [comment]
Alright, we have the go ahead from @marcuswhybrow. @endofcake you're now added as a collaborator, I'll ping him about adding you @renderorange.

We're now instituting an open commit bit with MSM. If you submit a pull request and it's merged, you'll get the commit bit on the repo. Please commit responsibly ;-).

**Comment by feross** [comment]
This idea originated with the LevelUP project. Here's what they have to say:

> Individuals making significant and valuable contributions are given commit-access to a project to contribute as they see fit. A project is more like an open wiki than a standard guarded open source project.

More here: https://github.com/Level/community/blob/master/CONTRIBUTING.md#level-projects-are-open-open-source-projects

:)

**Comment by endofcake** [comment]
@feross , @zachlatta  cool, lets hope this works out!

**Comment by endofcake** [comment]
Also, there are some PRs opened way back in 2012, should we start cleaning up the queue?

**Comment by zachlatta** [comment]
Let's go for it.

**Comment by zachlatta** [comment]
Should we revert this pull request now?

**Comment by endofcake** [comment]
@zachlatta , yeah, it looks like the project is no longer dead, although perhaps not actively developed.

**Comment by renderorange** [comment]
Indeed, this is going in a good direction.  I agree on the revert, multiple people have voiced interest in working the project :)

**Pull request merged**
